typos:
- ", that"
- "smart phone"
- "Smart phone"
- "signaling"
- "Signaling"
- "optimiz"
- "Optimiz"
- " \\cite"
- "trade-off"
- "trade off"
- "power consumption"
- "energy "
- "such as"
- "three state "
- "two state "
- "because"
- " he "
- " she "